name: Deploy idleminer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: SSH vorbereiten
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy mit rsync (nur dist Ordner)
        run: |
          rsync -avz --checksum --delete \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ./dist/ \
            ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.REMOTE_PATH }}/dist